export const Users = [
    {
        id: 1,
        profilePicture: "https://picsum.photos/50/50",
        username: "Gianluca Cobucci",
    },
    {
        id: 2,
        profilePicture: "https://picsum.photos/50/50",
        username: "Mario Rossi",
    },
    {
        id: 3,
        profilePicture: "https://picsum.photos/50/50",
        username: "Stefano Carlini",
    },
    {
        id: 4,
        profilePicture: "https://picsum.photos/50/50",
        username: "Giorgia Bianchi",
    },
    {
        id: 5,
        profilePicture: "https://picsum.photos/50/50",
        username: "Niccolò Verdi",
    },
    {
        id: 6,
        profilePicture: "https://picsum.photos/50/50",
        username: "Marco Ponzo",
    },
    {
        id: 7,
        profilePicture: "https://picsum.photos/50/50",
        username: "Costanza Berti",
    },
    {
        id: 8,
        profilePicture: "https://picsum.photos/50/50",
        username: "Alessandro Nervi",
    },
    {
        id: 9,
        profilePicture: "https://picsum.photos/50/50",
        username: "Gianni Storti",
    },
    {
        id: 10,
        profilePicture: "https://picsum.photos/50/50",
        username: "Aldo Baldi",
    },
];

export const Posts = [
    {
        id: 1,
        description: "Ciao, io mi chiamo XXX",
        photo: "https://picsum.photos/400/250",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "https://picsum.photos/400/250",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        description: "Every moment is a fresh beginning.",
        photo: "https://picsum.photos/400/250",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "https://picsum.photos/400/250",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "https://picsum.photos/400/250",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "https://picsum.photos/400/250",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        description: "Never regret anything that made you smile.",
        photo: "https://picsum.photos/400/250",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "https://picsum.photos/400/250",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        description: "Change the world by being yourself.",
        photo: "https://picsum.photos/400/250",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "https://picsum.photos/400/250",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];